[versions]
agp = "8.13.2"
androidx-activity = "1.12.2"
androidx-core = "1.17.0"
androidx-lifecycle = "2.10.0"
composeRulesDetekt = "0.5.3"
coroutines = "1.10.2"
detekt = "1.23.8"
google-coreLibraryDesugaring = "2.1.5"
ktlint = "1.8.0" # read by Foundry
kotlin = "2.3.0"
kotlinx-serialization = "1.9.0"
ksp = "2.3.0"
jdk = "21" # read by Foundry
junit = "4.13.2"
junitVersion = "1.3.0"
composeBom = "2025.12.01"
runner = "1.6.2"
coilCompose = "2.7.0"
accompanistPermissions = "0.37.3"
datastorePreferences = "1.2.0"
metro = "0.9.3"
nav3Core = "1.0.0"
slackFoundry = "0.33.1"
sortDependencies = "0.16"
spotless = "8.1.0"

[libraries]
accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanistPermissions" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material-icons-core = { group = "androidx.compose.material", name = "material-icons-core" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastorePreferences" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "androidx-lifecycle" }
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3Core" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3Core" }

coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coilCompose" }
detekt-compose-rules = { group = "io.nlopez.compose.rules", name = "detekt", version.ref = "composeRulesDetekt" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
google-coreLibraryDesugaring = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "google-coreLibraryDesugaring" } #read by Foundry
junit = { group = "junit", name = "junit", version.ref = "junit" }
metrox-android = { group = "dev.zacsweers.metro", name = "metrox-android", version.ref = "metro" }
metrox-viewmodel = { group = "dev.zacsweers.metro", name = "metrox-viewmodel", version.ref = "metro" }
metrox-viewmodel-compose = { group = "dev.zacsweers.metro", name = "metrox-viewmodel-compose", version.ref = "metro" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
foundry-root = { id = "com.slack.foundry.root", version.ref = "slackFoundry" }
foundry-base = { id = "com.slack.foundry.base", version.ref = "slackFoundry" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
metro = { id = "dev.zacsweers.metro", version.ref = "metro" }
sort-dependencies = { id = "com.squareup.sort-dependencies", version.ref = "sortDependencies" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
